spring:
  devtools:
    liveload:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: true

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
